### ISSUE TITLE
Can the model use biomass data instead of counts data？

### ISSUE THREAD

**Issue by Hanqingpeng** [smwoodman/eSDM#11]
Can the model use biomass data instead of counts data？

**Comment by smwoodman** [comment]
Thanks for the question - yes it should be fine to use biomass data. The overlay method uses an area-weighted average, and the evaluation metrics are not specific to a specific to a certain type of data. The one thing that comes to mind is making sure not to use the 'Abundance' rescaling method. Please let me know if I can clarify anything else.

**Comment by Hanqingpeng** [comment]
Thank you !  I have no more questions.
I am very interested in this method and will apply it to the distribution of fish in Bohai Sea of China

**Comment by smwoodman** [comment]
One other thing I forgot is specifying the 'Prediction value type'. If the units of the biomass data are a density, e.g. something/km2, then I would select 'absolute density'. If they are not per km2 or per m2, then you likely should select abundance. 

This is because the values need to be densities to do the overlay - if you select 'Abundance' when importing, then the eSDM GUI converts the values to a density by dividing by the areas of the corresponding grid cells. 

Good luck!
